#ifndef HEADER_CTR_DRBG_H
#define HEADER_CTR_DRBG_H

#include "YBCrypto.h"


#define SEEDLEN_128 BC_MAX_BLOCK_SIZE + 16
#define SEEDLEN_192 BC_MAX_BLOCK_SIZE + 24
#define SEEDLEN_256 BC_MAX_BLOCK_SIZE + 32

#define MAX_V_LEN_IN BC_MAX_BLOCK_SIZE
#define MAX_Key_LEN BC_MAX_KEY_SIZE 
#define MAX_SEEDLEN SEEDLEN_256 

#define STATE_INITIALIZED_FLAG 0x94500099

#endif
//EOF